[package]
name = "flappybird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
rand = "0.8.5"
bevy_rapier2d = {  version = "0.22.0", features = [ "simd-stable", "debug-render-2d" ] }
